package com.labs.server.service;

import com.labs.server.entity.ReportTemplate;
import com.labs.server.repository.ReportTemplateRepository;
import lombok.RequiredArgsConstructor;
import lombok.extern.slf4j.Slf4j;
import org.springframework.stereotype.Service;
import org.springframework.transaction.annotation.Propagation;
import org.springframework.transaction.annotation.Transactional;

import java.util.UUID;

/**
 * Separate bean for the report-template lazy seed so the @Transactional proxy
 * is actually applied — mirrors {@link LabServiceSeeder} for the same reason:
 * {@link ReportTemplateService} is {@code @Transactional(readOnly = true)} at
 * the class level, so an in-process save would be silently discarded.
 *
 * Calling {@code reportTemplateSeeder.seedFor(...)} from another bean goes
 * through Spring's AOP proxy, and {@link Propagation#REQUIRES_NEW} suspends
 * the readOnly parent transaction and opens a fresh writable one, so the
 * insert actually flushes.
 */
@Slf4j
@Service
@RequiredArgsConstructor
public class ReportTemplateSeeder {

    private final ReportTemplateRepository repository;

    @Transactional(propagation = Propagation.REQUIRES_NEW)
    public void seedDefaultFor(UUID hospitalId) {
        // Re-check inside the new transaction in case another request beat us.
        if (repository.countByHospitalId(hospitalId) > 0) {
            return;
        }
        ReportTemplate seeded = ReportTemplate.builder()
                .hospitalId(hospitalId)
                .name("ZenoLabs Default")
                .isDefault(true)
                .active(true)
                .accentColor("#14b8a6")
                .headerHtml("<div style='text-align:center;'><strong>Laboratory Report</strong></div>")
                .footerHtml("<div style='text-align:center;font-size:10px;color:#666;'>"
                        + "Generated by ZenoLabs &mdash; for queries contact your lab.</div>")
                .signatoryName("Authorised Signatory")
                .build();
        log.info("Seeding default report template for hospital {}", hospitalId);
        repository.save(seeded);
    }
}
