// Hospital-code prefix display helpers.
//
// Every human-readable record number generated by the backend carries a
// 4-digit hospital code prefix (e.g. "1001-ADM-2026-0001", "1001-IPD-2026-0004",
// "1001-MRN-2026-00012", "1001-12345678901234" for UHIDs). The prefix exists so
// that a single global search query can scope to a hospital across every app
// in the suite.
//
// Inside the per-hospital HMS UI the prefix is redundant — every record on
// screen already belongs to the logged-in hospital. Render-time stripping
// gives clinicians shorter, scannable IDs without losing the search property
// (the database column still stores the prefix; only the display is trimmed).
//
// IMPORTANT: do NOT call these helpers on values you intend to send back to
// the server. The backend treats the prefixed form as canonical.

const HOSPITAL_PREFIX_REGEX = /^\d{4}-/;

/**
 * Strips a leading "NNNN-" hospital prefix from an ID.
 *
 *   stripHospitalPrefix("1001-ADM-2026-0001")        → "ADM-2026-0001"
 *   stripHospitalPrefix("1001-12345678901234")        → "12345678901234"
 *   stripHospitalPrefix("ADM-2026-0001")              → "ADM-2026-0001"  (no-op, legacy IDs)
 *   stripHospitalPrefix("")                            → ""
 *   stripHospitalPrefix(null)                          → ""
 *   stripHospitalPrefix(undefined)                     → ""
 */
export function stripHospitalPrefix(id) {
  if (id === null || id === undefined) return "";
  const s = String(id);
  return s.replace(HOSPITAL_PREFIX_REGEX, "");
}

/**
 * Same as stripHospitalPrefix but returns null/undefined unchanged so it can be
 * used inside ternaries and JSX without converting empty values to "".
 *
 *   fmtId("1001-ADM-...")  → "ADM-..."
 *   fmtId(null)            → null
 *   fmtId(undefined)       → undefined
 */
export function fmtId(id) {
  if (id === null || id === undefined) return id;
  return String(id).replace(HOSPITAL_PREFIX_REGEX, "");
}
